### ISSUE TITLE
non lating symbols in topic

### ISSUE THREAD

**Issue by aur1mas** [fiverr/talking-capistrano#1]
If skype topic has non-latin symbols - it fails.

```
/Users/user/.rvm/gems/ruby-2.0.0-p0/gems/talking-capistrano-0.1.9/lib/skype_script_invoker.rb:27:in `split': invalid byte sequence in US-ASCII (ArgumentError)
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/talking-capistrano-0.1.9/lib/skype_script_invoker.rb:27:in `block in get_chat_id_for_topic'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/talking-capistrano-0.1.9/lib/skype_script_invoker.rb:26:in `each'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/talking-capistrano-0.1.9/lib/skype_script_invoker.rb:26:in `get_chat_id_for_topic'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/talking-capistrano-0.1.9/lib/skype_script_invoker.rb:9:in `initialize'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/talking-capistrano-0.1.9/lib/talking-capistrano.rb:18:in `new'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/talking-capistrano-0.1.9/lib/talking-capistrano.rb:18:in `set_notify'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/talking-capistrano-0.1.9/lib/talking-capistrano.rb:98:in `block (4 levels) in <top (required)>'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/capistrano-2.14.2/lib/capistrano/configuration/execution.rb:138:in `instance_eval'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/capistrano-2.14.2/lib/capistrano/configuration/execution.rb:138:in `invoke_task_directly'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/capistrano-2.14.2/lib/capistrano/configuration/callbacks.rb:25:in `invoke_task_directly_with_callbacks'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/capistrano-2.14.2/lib/capistrano/configuration/execution.rb:89:in `execute_task'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/capistrano-2.14.2/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/capistrano-2.14.2/lib/capistrano/callback.rb:38:in `call'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/capistrano-2.14.2/lib/capistrano/configuration/callbacks.rb:141:in `block in trigger'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/capistrano-2.14.2/lib/capistrano/configuration/callbacks.rb:141:in `each'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/capistrano-2.14.2/lib/capistrano/configuration/callbacks.rb:141:in `trigger'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/capistrano-2.14.2/lib/capistrano/configuration/callbacks.rb:23:in `invoke_task_directly_with_callbacks'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/capistrano-2.14.2/lib/capistrano/configuration/execution.rb:89:in `execute_task'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/capistrano-2.14.2/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/capistrano-2.14.2/lib/capistrano/cli/execute.rb:46:in `block in execute_requested_actions'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/capistrano-2.14.2/lib/capistrano/cli/execute.rb:45:in `each'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/capistrano-2.14.2/lib/capistrano/cli/execute.rb:45:in `execute_requested_actions'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/capistrano-2.14.2/lib/capistrano/cli/help.rb:19:in `execute_requested_actions_with_help'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/capistrano-2.14.2/lib/capistrano/cli/execute.rb:34:in `execute!'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/capistrano-2.14.2/lib/capistrano/cli/execute.rb:14:in `execute'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/capistrano-2.14.2/bin/cap:4:in `<top (required)>'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/bin/cap:23:in `load'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/bin/cap:23:in `<main>'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/user/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by AvnerCohen** [comment]
Slightly belated. :)
Thanks for reporting. I'll take a look.
